spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&connectTimeout=30000&socketTimeout=15000&autoReconnectForPools=true&allowMultiQueries=true&failOverReadOnly=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      minimumIdle: 5

mybatis-plus:
  configuration:
    default-statement-timeout: 20
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath*:/mapper/**/*.xml



